### ISSUE TITLE
Get key from env var if available

### ISSUE THREAD

**Issue by saamo** [luskhq/launchkit#1]
IMO, it would be better to read the key used for decryption from the environment variable from the _inside_ of the launchkit code. Now the key is visible in build logs because it's used as a parameter.

```
$ npm run deploy -- production --yes --key $LAUNCHKIT_KEY

> recruiter-browser-extension-app@0.1.0 deploy /home/ubuntu/recruiter-browser-extension-app
> launchkit deploy "production" "--yes" "--key" "abc123"
```

**Comment by arturmuller** [comment]
Good point. 👍 

So I think it should go as follows:

1. Accept key from `--key` (still useful for testing and such...). If not provided...
2. Try to read key from `LAUNCHKIT_KEY`. If not provided...
3. Try to read key from file using `--key-path` (defaults to `.key`). If not provided...
4. Blow up.

What do you think?
